### ISSUE TITLE
AV software moving tis file into quarantine

### ISSUE THREAD

**Issue by GeePee29** [kokolihapihvi/RockSniffer#13]
Since this morning Avira AV software reports rocksniffer.exe as an unknown HEUR/APC and quarantines it.

**Comment by kokolihapihvi** [comment]
Hey

I don't think there is much I can do about this, since rocksniffer by design reads process memory which could be interpreted as malicious by AV software.

Doing a bit of googling shows that the [HEUR](https://support.avira.com/hc/en-us/articles/360000819265-What-is-a-HEUR-virus-warning-) means it was analyzed somehow but not necessarily determined to be a virus. It looks like you can submit it to Avira for analysis if you want to be sure.

**Comment by GeePee29** [comment]
OK Thanks. I thought it might be out of your hands, but I thought you'd like to be aware.
