### ISSUE TITLE
Discord Rich Presence seems to struggle with RS1 songs

### ISSUE THREAD

**Issue by sdasda7777** [kokolihapihvi/RockSniffer#28]
Expected behaviour is to have current song author and name displayed.
What happens instead is that I get some other song displayed, when I have CDLCs from that musician it tends to display those.
To replicate playing songs from RS1 should be enough.

**Comment by sdasda7777** [comment]
Hey, this seems to be fixed as of 0.4.1. Not sure if it was 100 % intended, but thanks either way!!

**Comment by kokolihapihvi** [comment]
Hey, 0.4.1 did fix a parsing problem on rs1 dlc that appeared after the september update. Maybe that problem was somehow present in the past. Did you ever confirm that song details show up as intended through other outputs (any addon, output files)?

Anyway, thanks for letting me know that it started working for you.

**Comment by sdasda7777** [comment]
Through RPC, yep. Before it just showed the info of last song not from RS1.
