### ISSUE TITLE
You guys suck

### ISSUE THREAD

**Issue by sdasda7777** [kokolihapihvi/RockSniffer#32]
You seem to completely ignore issues and pull requests, yet have the audacity to upgrade the language version, making it harder for anyone to build. If there were no bugs, I wouldn't say a single word, but this is pretty infuriating.

**Comment by Farami** [comment]
Are you serious? This is an open source project. 
If you don't like the way this is being worked on, fork it and make it your own.
Nobody owes you anything.

**Comment by sdasda7777** [comment]
Dude, I'm aware of that, and of course it's unrealistic to expect that every single bug or feature request will be accepted and worked on.
My problem is exactly with what you are proposing. I wanted to fix few of the issues, but that would mean having to painstakingly go through the whole project and downgrade it, disregarding the fact that I don't really want to have to maintain a brand new fork either.
The point was not to demand them fixing some specific issues, but to point out that the upgrades, as far as I looked through the changes, didn't bring anything other than raising of the barrier and worsening of the compatibility.

**Comment by PoizenJam** [comment]
This is not a technical issue appropriate to report on GitHub. Your comment belays an incredible sense of entitlement.

None of us are paid to work on it. It’s a labor of love from players and streamers of the Rocksmith. Most of us—myself included—have full time jobs, families, and other hobbies. Like it or not, this project doesn’t pay the bills and is not any of our priority commitment. And to be frank, the project is already in a stable state that works for the vast majority of end-users without issue.

As suggested, if you have a problem you are free to maintain your own fork on the project. If you can do a better job, I implore you to do so. In fact, I joined the project precisely by suggesting a feature and bug fixing some others. Rather than demand something be fixed or added I actually contacted the devs to see how I could help, rather than flame them on the project page.

But saying ‘I don’t want to go through the whole project and downgrade it’- well, quite frankly, tough. We’re not going to do it for you. You don’t get to demand we do unpaid work on your terms.

Please check your massive sense of entitlement at the door in the future, and do not use the ‘Issues’ page on a GitHub project to air your grievances.

**Comment by sdasda7777** [comment]
Probably best to keep it short: I don't actually think you guys suck and I'm sorry for what I've said and how I made you feel.
